INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, BIRTH_PLACE) VALUES ('Czeslaw', 'Milosz', 'Warszawa');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, BIRTH_PLACE) VALUES ('Witold', 'Gombrowicz', 'Krakow');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, BIRTH_PLACE) VALUES ('Adam', 'Mickiewicz', 'Warszawa');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, BIRTH_PLACE) VALUES ('Henryk', 'Sienkiewicz', 'Krakow');